name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            svc-task-details-repository-manager:
              - 'svc-task-details-repository-manager/**'
      - name: Build
        run: cd ./svc-task-details-repository-manager && cargo build --verbose
      - name: Run tests
        run: cd ./svc-task-details-repository-manager && cargo test --verbose
